version: '3'

services:
  nginx:
    image: nginx:1.22-alpine
    ports:
      - "8000:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./:/code

  php:
    build: .
    volumes:
      - ./:/code
    depends_on:
      - mysql


  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: api_codeqr
      MYSQL_USER: root
      MYSQL_PASSWORD: root_password

volumes:
  mysql_data:
